<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KodeAkunSeeder extends Seeder
{
    public function run()
    {
        DB::table('kode_akun')->insert([
            [
                'company_id' => 1,
                'account_id' => '1101',
                'name' => 'Kas',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'NERACA',
                'debit' => 50000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '1102',
                'name' => 'Piutang Usaha',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'NERACA',
                'debit' => 30000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '1103',
                'name' => 'Sewa Dibayar Dimuka',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'NERACA',
                'debit' => 10000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '1104',
                'name' => 'Persediaan',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'NERACA',
                'debit' => 20000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '1201',
                'name' => 'Tanah',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'NERACA',
                'debit' => 100000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '2101',
                'name' => 'Utang',
                'helper_table' => '11',
                'balance_type' => 'CREDIT',
                'report_type' => 'NERACA',
                'debit' => null,
                'credit' => 40000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '2102',
                'name' => 'Utang Gaji',
                'helper_table' => '11',
                'balance_type' => 'CREDIT',
                'report_type' => 'NERACA',
                'debit' => null,
                'credit' => 5000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '3101',
                'name' => 'Modal',
                'helper_table' => '11',
                'balance_type' => 'CREDIT',
                'report_type' => 'NERACA',
                'debit' => null,
                'credit' => 150000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '4101',
                'name' => 'Pendapatan Jasa',
                'helper_table' => '11',
                'balance_type' => 'CREDIT',
                'report_type' => 'LABARUGI',
                'debit' => null,
                'credit' => 70000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '5101',
                'name' => 'Beban Gaji',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'LABARUGI',
                'debit' => 15000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '5102',
                'name' => 'Beban Sewa',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'LABARUGI',
                'debit' => 8000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '5103',
                'name' => 'Beban Lain-Lain',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'LABARUGI',
                'debit' => 5000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'account_id' => '5104',
                'name' => 'Beban Persediaan',
                'helper_table' => '11',
                'balance_type' => 'DEBIT',
                'report_type' => 'LABARUGI',
                'debit' => 7000000.00,
                'credit' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
